config/routes.rb
Firstapp::Application.routes.draw do
  resources :comments
  devise_for :users
  resources :my_recipes do 
    resources :comments
  end
  resources :profiles, only: [:index, :show]
  resources :site, only: [:index, :show, :search] do 
    resources :comments
  end
  resources :site_recipes, only: [:index, :show, :search] do 
    resources :comments
  end

  resources :ratings, only: [:update]
  post '/search' => 'site_recipes#search', as: :search

  root 'site_recipes#index'

end

app/models/site_recipe.rb
class SiteRecipe < ActiveRecord::Base
  paginates_per 12
  has_many :comments, as: :commentable
  has_many :ratings

  def average_rating
  ratings.sum(:score) / ratings.size
end

end

app/controllers/site_recipes_controller.rb
class SiteRecipesController < ApplicationController
  include ActionView::Helpers::TextHelper
  before_action :authenticate_user!, except: [:index,:show,:search]
  def index
    @siterecipes = SiteRecipe.order('created_at desc').page(params[:page])
    #display some recipes that were created by former search results.
  end

  def search
    agent = Mechanize.new
    
    url = "http://www.epicurious.com/tools/searchresults?search=#{params[:food]}&type=simple&sort=3&pageNumber=1&pageSize=12"
    url_params = params[:food]
    if url_params == nil
    url = "http://www.epicurious.com/tools/searchresults?search=#{params[:foodnav]}&type=simple&sort=3&pageNumber=1&pageSize=12"
    end
    #Epicurus search url is passed the user's search input.
    page = agent.get(url)
    #mechanize is getting data from the url.
    box_preparation = []
    box_preparation_temp = []
    box_ingredient =[]
    box_ingredient_temp =[]
    box_image = []
    box_source = []
    box_nutrition = []
    box_nutrition_temp = []
    box_summary = []
    box_calorie = []
    box_serving = []
    box_total_time =[]
    box_active_time = []
    box_fat = []
    box_poly= []
    box_mono = []
    box_saturated = []
    box_protein = []
    box_carb= []
    box_sodium = []
    box_fiber = []
    box_cholesterol = []

    #creating arrays to store the desired information from the search page for instantiating Site Recipes.


    temp = []
    #temporary array to hold links to every recipe found in the Epicurus search result.
    page.search("a.recipeLnk").each do |link|
      temp << link.attr('href')
      #Add each recipe's link to the temporary array so mechanize can visit those links.
    end

    box_title = []
    page.search("a.recipeLnk").each do |link|
      box_title << link.text
      #Add the recipe title to the array.
    end

    i = 0
    while i < temp.size
      link = page.link_with(href: temp[i]).click
      #mechanize will visit each link that was stored in the temporary array.
      box_preparation_temp = link.parser.css("#preparation").text
      box_preparation << box_preparation_temp.gsub("Preparation","")

      link.search(".ingredient").each do |food|
        box_ingredient_temp << food.text
      end
      box_ingredient_temp = box_ingredient_temp.join(",")
      box_ingredient << box_ingredient_temp.gsub(",","\n")
      
      box_source << link.parser.css(".source").text
        link.search(".nutriData").each do |nutrition|
          box_nutrition << nutrition.text
        end
            j = 0
            while j < box_nutrition.size
              box_nutrition[j].sub!(/\n/,"")
              if box_nutrition[j] == nil
                box_nutrition[j] = "N/A"
                end
               j +=1
            end

       
if box_nutrition[0].nil?
  box_nutrition[0] = "N/A" 
  box_calorie << box_nutrition[0]  
  else  
    box_calorie << box_nutrition[0]
  end

if box_nutrition[1].nil?
  box_nutrition[1] = "N/A" 
  box_carb << box_nutrition[1]  
  else  
    box_carb << box_nutrition[1]
  end
    

    if box_nutrition[2].nil?
  box_nutrition[2] = "N/A" 
  box_fat << box_nutrition[2]  
  else  
    box_fat << box_nutrition[2]
  end

    if box_nutrition[3].nil?
  box_nutrition[3] = "N/A" 
  box_protein << box_nutrition[3]  
  else  
    box_protein << box_nutrition[3]
  end
    
    if box_nutrition[4].nil?
  box_nutrition[4] = "N/A" 
  box_saturated << box_nutrition[4]  
  else  
    box_saturated << box_nutrition[4]
  end
    
    if box_nutrition[5].nil?
  box_nutrition[5] = "N/A" 
  box_sodium << box_nutrition[5]  
  else  
    box_sodium << box_nutrition[5]
  end

if box_nutrition[6].nil?
  box_nutrition[6] = "N/A" 
  box_poly << box_nutrition[6]  
  else  
    box_poly << box_nutrition[6]
  end

    if box_nutrition[7].nil?
  box_nutrition[7] = "N/A" 
  box_fiber << box_nutrition[7]  
  else  
    box_fiber << box_nutrition[7]
  end

    if box_nutrition[8].nil?
  box_nutrition[8] = "N/A" 
  box_mono << box_nutrition[8]  
  else  
    box_mono << box_nutrition[8]
  end

    if box_nutrition[9].nil?
  box_nutrition[9] = "N/A" 
  box_cholesterol << box_nutrition[9]  
  else  
    box_cholesterol << box_nutrition[9]
  end


    if link.parser.css("p.summary_data")[0].nil?
      box_serving_temp = "N/A"
    else
    box_serving_temp = link.parser.css("p.summary_data")[0].text
  end
    box_serving_temp = box_serving_temp.strip
    box_serving_temp =  box_serving_temp.gsub("\n","")
    box_serving_temp = box_serving_temp.gsub("yieldMakes","")
    box_serving <<  box_serving_temp[1] + box_serving_temp[2]
    box_active_time = "N/A"
    box_total_time = "N/A"
      photo =  link.parser.css('img.photo')
      #mechanize parses the data from the page and gets the text value of the
      #desired css element. The data gets stored in the respective arrays.
      if photo.empty?
        box_image << '/images/articlesguides/howtocook/cookbooks/best-cookbooks-2012_612.jpg'
        #if the recipe page does not have an image, use some other Epicurus image.
      else
        box_image << photo.attr('src').text
      end
      box_ingredient_temp = []
      box_nutrition = []
      box_serving_temp = []
      agent.back
      #Mechanize goes back to the search result page, and then can
      #click on the next link in the temporary array.
      i +=1
    end

    i = 0
    while i < temp.size
      SiteRecipe.create(title: "#{box_title[i]}", 
        ingredients: "#{box_ingredient[i]}", 
        preparation: "#{box_preparation[i]}", 
        image: "#{box_image[i]}", 
        source: "#{box_source[i]}", 
        fat: "#{box_fat[i]}", 
        calories: "#{box_calorie[i]}", 
        protein: "#{box_protein[i]}",
      saturated: "#{box_saturated[i]}",
      sodium: "#{box_sodium[i]}",
      poly: "#{box_poly[i]}",
      mono: "#{box_mono[i]}",
      carb: "#{box_carb[i]}",
      fiber: "#{box_fiber[i]}",
      servings: "#{box_serving[i]}",
      cholesterol: "#{box_cholesterol[i]}")
      i +=1
      #Create a Site Recipe from the data scraped from Epicurus by Mechanize. Should only create if a new entry.
    end

    @recipes = SiteRecipe.last(12)
  end


  def show
    @recipes = SiteRecipe.find(params[:id])
    @image = @recipes.image
    @ingredients = @recipes.ingredients
    @preparation = @recipes.preparation
    @description =@ingredients + @preparation
    @calories = @recipes.calories
    @protein = @recipes.protein
    @fat = @recipes.fat
    @saturated = @recipes.saturated
    @poly = @recipes.poly
    @sodium = @recipes.sodium
    @mono= @recipes.mono
    @cholesterol = @recipes.cholesterol
    @carb = @recipes.carb
    @fiber = @recipes.fiber
    @serving = @recipes.servings
    #creating instance variables for the recipe page to be displayed in the view.
    AWS::S3::Base.establish_connection!(
      :access_key_id     => ENV['S3_KEY'],
    :secret_access_key => ENV['S3_SECRET'])
    #Establishing connection to Amazon S3 account.
    bucket = AWS::S3::Bucket.find("tennis-testing")
    #Find S3 bucket that will store audio file.
    file = @description.to_file "en", "app/assets/audios/#{@recipes.title}.mp3"
    #Create an audio file from the recipe's ingredient list and cooking instructions. Set language and file path.
    @audio = "app/assets/audios/#{@recipes.title}.mp3"
    #Store the audio file's path.
    @title = @recipes.title.gsub(/\s/,"+")
    #Replace any spaces in the recipes title with addition symbol.
    AWS::S3::S3Object.store(@audio, open(@audio), 'tennis-testing')
    #Upload the audio file to S3.
    File.delete("#{Rails.root}/app/assets/audios/#{@recipes.title}.mp3")
    #Remove the local copy of audio file.
    @commentable = @recipes
  @comments = @commentable.comments
  @comment = Comment.new
  if current_user == nil
   @current_user = User.first
  else
    @current_user = current_user.id   
  end

@rating = Rating.where(site_recipe_id: @recipes.id, user_id: @current_user).first unless @rating 
@rating = Rating.create(site_recipe_id: @recipes.id, user_id: @current_user, score: 0)
  end
end

app/helpers/site_recipes_helper.rb
module SiteRecipesHelper
end

app/views/site_recipes/_recipes.html.erb
<tr class="epirecipes">
  <td><%= @siterecipes.title %></td>
  <td><%= @siterecipes.source %></td>
</tr>

app/views/site_recipes/index.html.erb
<nav class="navbar navbar-fixed-top stitched" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SousChef</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "My profile", my_recipes_path %></li>
            <li><%= link_to 'New Recipe', new_my_recipe_path%></li>
                <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in",  new_user_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

<div class="bgSizeCover container-fluid" data-stellar-background-ratio="0.5">
  <p class="center" id="search_bar">Let SousChef read the recipe while you cook.</p>
  <%= form_tag search_path, :class => "center" do %>
    <%= label_tag() %>
    <%= text_field_tag(:food) %><br>
    <%= submit_tag "Search", class: 'search_button'%>
  <% end %>
</div>
<div class="panel2a">
  <div class="container">
    <div class="row-fluid">
      <div class="col-md-4">
        <div class="circle center-block"></div>
        <img class="center-block" id="cooking" src="/assets/cooking.png">
        <h2>Your Personal Helper</h2>
        <p>SousChef takes care of reading the recipe so you don't have to, and you can focus more on cooking. Instead of frantically searching for your place in the recipe and getting your device dirty, SousChef can be hands free. You can scroll through the recipe and pause the sound with a small wave of a finger. SousChef will change the way you cook with a recipe.  
        </p>
      </div>
      <div class="col-md-4">
        <div class="circle center-block"></div>
        <img class="center-block" id="speaker" src="/assets/speaker.png">
        <h2>Text To Speech</h2>
        <p>Instead of having to read recipes, SousChef will do it for you. It turns the recipe you search for, or your own submissions into audio. You can make the sound
          as loud as you need, and stop it at any point. It'll feel like having your own
          personal chef in the kitchen helping you along. 
        </p>
      </div>
      <div class="col-md-4">
        <div class="circle center-block "></div>
        <img class="center-block" id="webcam" src="/assets/webcam.png">
        <h2>Motion Detection</h2>
        <p>If you like reading recipes off devices while you cook, there's the risk of getting them dirty. SousChef helps you by making the experience as hands free 
        as possible. Not only does SousChef read the recipe, but you can also control the audio and scrolling with the wave of your hand-literally. SousChef uses your webcam to display a screen with controls that you control by waving over them. No touching necesssary.  </p>
      </div>
    </div>
  </div>
</div>
<div class="panel2" data-stellar-background-ratio="0.5">
  <div class="container-fluid">
     <h1 style="color:white">Watch A Demo of SousChef In Action!</h1>
    <iframe width="1280" height="600" src="//www.youtube.com/embed/mbfPwvcw4Oc" frameborder="0" allowfullscreen></iframe>
  </div>
</div>
<div class="panel3 center" data-stellar-background-ratio="0.4">
  <% @siterecipes.each do |recipe| %>
    <div id="masonry-container_index">
      <a href="<%= site_recipe_path(recipe)%>">
        <div class="box col4">
          <img src="http://www.epicurious.com<%= recipe.image %>">
          <div class="row">
            <div class="col-xs-12"><%= recipe.title %></div>
          <div class="col-xs-12" id="index_source_home"><%= recipe.source %></div>
          <div class="col-xs-4 col-lg-3 index_info"><h1 class="info_value"><%= recipe.calories %></h1><h2 class="info_title">Calories</h2></div>
           <div class="col-xs-4  col-lg-3 index_info" id="recipe_info_bg"><h1 class="info_value">N/A</h1><h2 class="info_title">Time</h2></div>
            <div class="col-xs-4 col-lg-3 index_info" ><h1 class="info_value"><%= recipe.servings%></h1><h2 class="info_title">Serving</h2></div>
        </div>
        </div>
      </a>
    </div>
  <% end %>
</div>
  <div id="signup-panel">
    <div class="container-fluid">
      <h2 id="signup-title1">JOIN FOR FREE!</h1>
      <h3 id="signup-title3">BE IN CONTROL OF YOUR KITCHEN</h1>
      <h1 id="signup-title2">ADD YOUR OWN RECIPES TO SOUSCHEF</h1>
      <li id="signup-button"><%= link_to "Sign up", new_user_registration_path %></li>


   </div>

   </div>
</div>

app/views/site_recipes/result.html.erb
<nav class="navbar navbar-fixed-top stitched" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SousChef</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "My profile", my_recipes_path %></li>
            <li><%= link_to 'New Recipe', new_my_recipe_path%></li>
                <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in",  new_user_session_path %></li>
              <% end %>
              <%= form_tag search_path, :class => "center" do %>
                    <%= label_tag() %>
                    <%= text_field_tag(:foodnav, "Search recipes...") %><br>
                    <%= submit_tag "", :id=> "navsearch"%>
                  <% end %>
            </ul>
          </div>
        </div>
      </nav>
<h2>result.html.erb</h2>
<%= @recipes %>

app/views/site_recipes/search.html.erb
<nav class="navbar navbar-fixed-top stitched" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SousChef</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "My profile", my_recipes_path %></li>
            <li><%= link_to 'New Recipe', new_my_recipe_path%></li>
                <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in",  new_user_session_path %></li>
              <% end %>
              <%= form_tag search_path, :class => "center" do %>
                    <%= label_tag() %>
                    <%= text_field_tag(:foodnav, "Search recipes...") %><br>
                    <%= submit_tag "", :id=> "navsearch"%>
                  <% end %>
            </ul>
          </div>
        </div>
      </nav>
<h2 id="result_title">Your Results:</h2>
<div class="container-fluid">
  <% @recipes.each do |recipe| %>
    <div id="masonry-container-search" class="transitions-enabled infinite-scroll clearfix">
      <a href="<%= site_recipe_path(recipe)%>">
      <div class="box col4">
          <img src="http://www.epicurious.com<%= recipe.image %>">
          <div id="star_search_mobile" title="Not rated yet!">
<img alt="1" src="/assets/star-off.png" title="Not rated yet!">&nbsp;<img alt="2" src="/assets/star-off.png" title="Not rated yet!">&nbsp;<img alt="3" src="/assets/star-off.png" title="Not rated yet!">&nbsp;<img alt="4" src="/assets/star-off.png" title="Not rated yet!">&nbsp;<img alt="5" src="/assets/star-off.png" title="Not rated yet!"><input name="score" type="hidden" readonly=""></div>
          <div class="row">
            <div class="col-xs-12"><h2 id="search_recipe_title"><%= recipe.title %></h2></div>
          <div class="col-xs-12" id="index_source" style="color:white;"><%= recipe.source %></div>
          <div class="col-xs-4 col-lg-3 index_info_search"><h1 class="info_value" id="search_recipe_calories_value"><%=recipe.calories%></h1><h2 class="info_title" id="search_recipe_calories_title">Calories</h2></div>
           <div class="col-xs-4  col-lg-3 index_info_search" id="recipe_info_bg"><h1 class="info_value" id="search_recipe_time_value">N/A</h1><h2 class="info_title" id="search_recipe_time_title">Time</h2></div>
            <div class="col-xs-4 col-lg-3 index_info_search" ><h1 class="info_value" id="search_recipe_serving_value"><%=recipe.servings%></h1><h2 class="info_title" id="search_recipe_serving_title">Serving</h2></div>
        </div>
        </div>
      </a>
    </div>
  <% end %>