config/routes.rb
Firstapp::Application.routes.draw do
  resources :comments
  devise_for :users
  resources :my_recipes do 
    resources :comments
  end
  resources :profiles, only: [:index, :show]
  resources :site, only: [:index, :show, :search] do 
    resources :comments
  end
  resources :site_recipes, only: [:index, :show, :search] do 
    resources :comments
  end

  resources :ratings, only: [:update]
  post '/search' => 'site_recipes#search', as: :search

  root 'site_recipes#index'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def show
    if @user = User.where(id: params[:id]).first # returns User object. Returns nil when not found.
      @myrecipes = @user.my_recipes.page(params[:page]) #to display user's recipe.
    else
      flash[:alert] = 'Profile not found.'
      redirect_to profiles_path
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/index.html.erb
<nav class="navbar navbar-fixed-top stitched" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SousChef</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "My profile", my_recipes_path %></li>
            <li><%= link_to 'New Recipe', new_my_recipe_path%></li>
                <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in",  new_user_session_path %></li>
              <% end %>
              <%= form_tag search_path, :class => "center" do %>
                    <%= label_tag() %>
                    <%= text_field_tag(:foodnav, "Search recipes...") %><br>
                    <%= submit_tag "", :id=> "navsearch"%>
                  <% end %>
            </ul>
          </div>
        </div>
      </nav>
<h2>Users that joined</h2>
<table style="width: 100%">
  <thead>
    <tr>
      <th>User</th>
      <th># Recipes</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, profile_path(user) %></td>
        <td><%= user.my_recipes.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/profiles/show.html.erb
<nav class="navbar navbar-fixed-top stitched" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SousChef</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "My profile", my_recipes_path %></li>
            <li><%= link_to 'New Recipe', new_my_recipe_path%></li>
                <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in",  new_user_session_path %></li>
              <% end %>
              <%= form_tag search_path, :class => "center" do %>
                    <%= label_tag() %>
                    <%= text_field_tag(:foodnav, "Search recipes...") %><br>
                    <%= submit_tag "", :id=> "navsearch"%>
                  <% end %>
            </ul>
          </div>
        </div>
      </nav>
<h2>Recipes submitted by
  <%= link_to @user.email, profile_path(@user) %></h2>
<table style="width: 100%">
  <thead>
    <tr>
      <th>Recipe</th>
      <th>User</th>
    </tr>
  </thead>
  <tbody>
    <% @myrecipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.title, recipe.url %></td>
        <td><%= link_to @user.email, profile_path(@user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @myrecipes %>
<%= link_to 'Back', profiles_path %>