config/routes.rb
Firstapp::Application.routes.draw do
  resources :comments
  devise_for :users
  resources :my_recipes do 
    resources :comments
  end
  resources :profiles, only: [:index, :show]
  resources :site, only: [:index, :show, :search] do 
    resources :comments
  end
  resources :site_recipes, only: [:index, :show, :search] do 
    resources :comments
  end

  resources :ratings, only: [:update]
  post '/search' => 'site_recipes#search', as: :search

  root 'site_recipes#index'

end

app/models/my_recipe.rb
class MyRecipe < ActiveRecord::Base
	before_save :set_recipe
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :ratings
  paginates_per 25
  validates :title, presence: true
  validates :ingredients, presence: true
  validates :preparation, presence: true

 def average_rating
  if ratings.size == 0
    ratings.sum(:score)
  else
  ratings.sum(:score) / ratings.size
end
end


def set_recipe
  self.sodium = "N/A" if self.sodium.blank?
  self.fat = "N/A" if self.fat.blank?
  self.calories = "N/A" if self.calories.blank?
  self.protein = "N/A" if self.protein.blank?
  self.time = "N/A" if self.time.blank?
  self.servings = "N/A" if self.servings.blank?
  self.mono = "N/A" if self.mono.blank?
  self.poly = "N/A" if self.poly.blank?
  self.fiber = "N/A" if self.fiber.blank?
  self.carb = "N/A" if self.carb.blank?
  self.cholesterol = "N/A" if self.cholesterol.blank?
  self.saturated = "N/A" if self.saturated.blank?
end


end

app/controllers/my_recipes_controller.rb
class MyRecipesController < ApplicationController
  require 'net/http'
  require 'json'
  require 'tts'
  require 'nokogiri'
  require 'open-uri'

  require 'mechanize'

  before_action :set_my_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /my_recipes
  def index
    @myrecipes = current_user.my_recipes.order('created_at desc').page(params[:page])
    @username = current_user.username
  end

  # GET /my_recipes/1
  def show
    @username = current_user.username
    @recipes = MyRecipe.find(params[:id])
    @image = @recipes.photo
    @ingredients = @recipes.ingredients
    @preparation = @recipes.preparation
    @description =@ingredients + @preparation
    @calories = @recipes.calories
    @protein = @recipes.protein
    @fat = @recipes.fat
    @saturated = @recipes.saturated
    @poly = @recipes.poly
    @sodium = @recipes.sodium
    @mono= @recipes.mono
    @cholesterol = @recipes.cholesterol
    @carb = @recipes.carb
    @fiber = @recipes.fiber
    @serving = @recipes.servings
    #@ingredients = @myrecipes.ingredients
    #@preparation = @myrecipes.preparation
    #@description =@ingredients + @preparation
    AWS::S3::Base.establish_connection!(
      :access_key_id     => ENV['S3_KEY'],
    :secret_access_key => ENV['S3_SECRET'])
    #Establish connection to Amazon S3 account.
    bucket = AWS::S3::Bucket.find("tennis-testing")
    #Find S3 bucket to store audio file.
    @file = @myrecipes.description.to_file "en", "app/assets/audios/#{@myrecipes.title+@username}.mp3"
    #Create the audio file of the recipe's cooking information and set language and file path.
    @myrecipes.speechlink = "app/assets/audios/#{@myrecipes.title+@username}.mp3"
    #Add the local path of audio file to the recipe object.
    @title = @myrecipes.title.gsub(/\s/,"+")+@username
    AWS::S3::S3Object.store(@myrecipes.speechlink, open(@myrecipes.speechlink), 'tennis-testing')
    #Upload the recipe audio file to S3.
    File.delete("#{Rails.root}/app/assets/audios/#{@myrecipes.title+@username}.mp3")
    @commentable = @recipes
  @comments = @commentable.comments
  @comment = Comment.new
  if current_user == nil
   @current_user = User.first
  else
    @current_user = current_user.id   
  end

@rating = Rating.where(site_recipe_id: @recipes.id, user_id: @current_user).first unless @rating 
@rating = Rating.create(site_recipe_id: @recipes.id, user_id: @current_user, score: 0)
  end

  # GET /my_recipes/new
  def new
    @myrecipes = current_user.my_recipes.new
  end

  # GET /my_recipes/1/edit
  def edit
  end

  # POST /my_recipes
  def create
    @myrecipes = current_user.my_recipes.new(my_recipes_params)
    @myrecipes.description = @myrecipes.ingredients+@myrecipes.preparation
    if @myrecipes.save
      redirect_to @myrecipes, notice: 'Recipe was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /my_recipes/1
  def update
    @username = current_user.username
    @myrecipes = MyRecipe.find(params[:id])
    AWS::S3::Base.establish_connection!(
      :access_key_id     => ENV['S3_KEY'],
    :secret_access_key => ENV['S3_SECRET'])
    #Establish connection to S3.
    bucket = AWS::S3::Bucket.find("tennis-testing")
    @myrecipes.speechlink = "app/assets/audios/#{@myrecipes.title+@username}.mp3"
    @title = @myrecipes.title.gsub(/\s/,"+")+@username
    AWS::S3::S3Object.delete(@myrecipes.speechlink, 'tennis-testing')
    #Delete the old audio file from S3 bucket.
    if @myrecipes.update(my_recipes_params)
      @file = @myrecipes.description.to_file "en", "app/assets/audios/#{@myrecipes.title+@username}.mp3"
      #Create a new audio file from updated recipe information.
      @myrecipes.speechlink = "app/assets/audios/#{@myrecipes.title+@username}.mp3"
      AWS::S3::S3Object.store(@myrecipes.speechlink, open(@myrecipes.speechlink), 'tennis-testing')
      #Upload the new audio file to S3.
      File.delete("#{Rails.root}/app/assets/audios/#{@myrecipes.title+@username}.mp3")
      #Delete the local audio file.
      redirect_to @myrecipes, notice: 'Recipe was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /my_recipes/1
  def destroy
    @myrecipes.destroy
    redirect_to my_recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_my_recipe
    unless @myrecipes = current_user.my_recipes.where(id: params[:id]).first
      flash[:alert] = 'Recipe not found.'
      redirect_to root_url
    end
  end

  # Only allow a trusted parameter "white list" through.
  def my_recipes_params
    params.require(:my_recipe).permit(:title, :description, :user_id, :photo, :search, :ingredients, :preparation, :servings, :time, :calories, :fat, :saturated, :poly, :mono, :carb, :protein, :sodium, :fiber, :cholesterol)
  end
end

app/helpers/my_recipes_helper.rb
module MyRecipesHelper
  AWS::S3::Base.establish_connection!(
    :access_key_id     => ENV['S3_KEY'],
  :secret_access_key => ENV['S3_SECRET'])

  def download_url_for(file)
    @file = 'app/assets/audios/#{@myrecipes.title}.mp3'
    AWS::S3::S3Object.url_for(@file, 'tennis-testing', :authenticated => false)
  end

end

app/views/my_recipes/edit.html.erb
<nav class="navbar navbar-fixed-top stitched" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SousChef</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "My profile", my_recipes_path %></li>
            <li><%= link_to 'New Recipe', new_my_recipe_path%></li>
                <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in",  new_user_session_path %></li>
              <% end %>
              <%= form_tag search_path, :class => "center" do %>
                    <%= label_tag() %>
                    <%= text_field_tag(:foodnav, "Search recipes...") %><br>
                    <%= submit_tag "", :id=> "navsearch"%>
                  <% end %>
            </ul>
          </div>
        </div>
      </nav>
           <div id="new_recipe">
<div class="container-fluid">
  <div id="new_recipe_form">
    <div class="row">
      <div class="span12 center">
        <h1 id="new_recipe_title">Edit Recipe</h1>
        <%= form_for(@myrecipes) do |f|  %>
          <% unless @myrecipes.errors.count == 0   %>
            <div class="alert alert-error">
              The form contains
              <%= pluralize(@user.errors.count, "error") %>.
            </div>
            <ul>
              <% @myrecipes.errors.full_messages.each do |msg| %>
                <li>*
                  <%= msg %></li>
              <% end %>
            </ul>
          <% end %>
          <div class="col-lg-4">
          <div><%= f.label :title, class: "center", style: "color:#333" %><br>
            <%= f.text_field :title, class: "center", style: "color: tomato; background-color:#333; border:none; width:80%;" %></div>
          <div><%= f.label :ingredients, "Ingredients", class: "center", style: "color:#333"%><br>
            <%= f.text_area :ingredients, class: "center", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :preparation, "Instructions",class: "center", style: "color:#333"%><br>
            <%= f.text_area :preparation, class: "center", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
             <div><%= f.label :photo,class: "center", style: "color:#333"%><br>
            <%= f.file_field :photo, style: "color: tomato;" %></div><br>
            </div>
             <div class="col-lg-4">
            <div><%= f.label :time,"Time",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :time, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :servings,"Servings",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :servings, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :calories,"Calories",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :calories, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :fat,"Fat",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :fat, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :protein,"Protein",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :protein, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :saturated,"Saturated Fat",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :saturated, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            </div>
             <div class="col-lg-4">
            <div><%= f.label :poly,"Polyunsaturated Fat",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :poly, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :mono,"Monounsaturated Fat",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :mono, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
             <div><%= f.label :carb,"Carbohydrates",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :carb, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :fiber,"Fiber",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :fiber, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :sodium,"Sodium",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :sodium, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
             <div><%= f.label :cholesterol,"Cholesterol",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :cholesterol, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            </div>
          <div><%= f.submit "Edit Recipe", class: "form_button", style: "margin-top:35px; margin-bottom:15px;" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/my_recipes/index.html.erb
<nav class="navbar navbar-fixed-top stitched" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SousChef</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "My profile", my_recipes_path %></li>
            <li><%= link_to 'New Recipe', new_my_recipe_path%></li>
                <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in",  new_user_session_path %></li>
              <% end %>
              <%= form_tag search_path, :class => "center" do %>
                    <%= label_tag() %>
                    <%= text_field_tag(:foodnav, "Search recipes...") %><br>
                    <%= submit_tag "", :id=> "navsearch"%>
                  <% end %>
            </ul>
          </div>
        </div>
      </nav>
        <div class="profile_background" style="height: auto;background-color:tan; min-height:650px;">
<div class="container-fluid">
<div class="row">
<div class="profile_container col-lg-4 col-xs-12">
<div id="profile_pic"> <%= image_tag(current_user.avatar_url) if current_user.avatar? %></div>
<div id="username"><%= @username %></div>
<br>
</div>
<div class="col-lg-8 col-xs-6">

  <h2 id="profile_recipe_header">Your Recipes:</h2>
    <div class="profile_recipe">
<% @myrecipes.each do |recipe| %>
  <div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
    <div class="box col3">
      <%= image_tag recipe.photo_url %>
      <h4>
      <%= recipe.title %>
    </h4>
      <br>
      <%= link_to 'Show', recipe %>
      <%= link_to 'Edit', edit_my_recipe_path(recipe) %>
      <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>
</div>
</div>
</div>
</div>
</div>
<%= paginate @myrecipes %>

app/views/my_recipes/new.html.erb
<nav class="navbar navbar-fixed-top stitched" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SousChef</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "My profile", my_recipes_path %></li>
            <li><%= link_to 'New Recipe', new_my_recipe_path%></li>
                <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in",  new_user_session_path %></li>
              <% end %>
              <%= form_tag search_path, :class => "center" do %>
                    <%= label_tag() %>
                    <%= text_field_tag(:foodnav, "Search recipes...") %><br>
                    <%= submit_tag "", :id=> "navsearch"%>
                  <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div id="new_recipe">
<div class="container-fluid">
  <div id="new_recipe_form">
    <div class="row">
      <div class="span12 center">
        <h1 id="new_recipe_title">New Recipe</h1>
        <%= form_for(@myrecipes) do |f|  %>
          <% unless @myrecipes.errors.count == 0   %>
            <div class="alert alert-error">
              The form contains
              <%= pluralize(@user.errors.count, "error") %>.
            </div>
            <ul>
              <% @myrecipes.errors.full_messages.each do |msg| %>
                <li>*
                  <%= msg %></li>
              <% end %>
            </ul>
          <% end %>
          <div class="col-lg-4">
          <div><%= f.label :title, class: "center", style: "color:#333" %><br>
            <%= f.text_field :title, class: "center", style: "color: tomato; background-color:#333; border:none; width:80%;" %></div>
          <div><%= f.label :ingredients, "Ingredients", class: "center", style: "color:#333"%><br>
            <%= f.text_area :ingredients, class: "center", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :preparation, "Instructions",class: "center", style: "color:#333"%><br>
            <%= f.text_area :preparation, class: "center", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
             <div><%= f.label :photo,class: "center", style: "color:#333"%><br>
            <%= f.file_field :photo, style: "color: tomato;" %></div><br>
            </div>
             <div class="col-lg-4">
            <div><%= f.label :time,"Time",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :time, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :servings,"Servings",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :servings, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :calories,"Calories",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :calories, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :fat,"Fat",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :fat, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :protein,"Protein",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :protein, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :saturated,"Saturated Fat",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :saturated, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            </div>
             <div class="col-lg-4">
            <div><%= f.label :poly,"Polyunsaturated Fat",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :poly, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :mono,"Monounsaturated Fat",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :mono, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
             <div><%= f.label :carb,"Carbohydrates",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :carb, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :fiber,"Fiber",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :fiber, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            <div><%= f.label :sodium,"Sodium",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :sodium, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
             <div><%= f.label :cholesterol,"Cholesterol",class: "center", style: "color: #333;"%><br>
            <%= f.text_field :cholesterol, class: "center", placeholder: "Not Available", style: "color: tomato; background-color:#333; border:none; width:80%;"%></div>
            </div>
          <div><%= f.submit "Create my recipe", class: "form_button", style: "margin-top:35px; margin-bottom:15px;" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>